### ISSUE TITLE
No ColorColumn value

### ISSUE THREAD

**Issue by bwells** [TroyFletcher/vim-colors-synthwave#1]
Vim's default ColorColumn value seems to be bright red, which is quite jarring against this scheme.

I'm still playing around with what color works well for it, but for now i've settled on the dark blue. 

`hi ColorColumn guifg=None guibg=#536991 guisp=None ctermfg=None ctermbg=60 cterm=NONE`

Thanks for the great color scheme.

**Comment by TroyFletcher** [comment]
Great find! I rarely use ColorColumn, so I never would have caught it.

Adding!
